//
//  VitaminSceneID.h
//  VitaminProject
//
//  Created by Shinji Hiramatsu on 2014/05/24.
//  Copyright 2014 GCREST,Inc. All rights reserved.
//

#ifdef DEF_SCENE_TYPE

DEF_SCENE_TYPE_1(SCENE_NONE, kVitaminSceneIDPrefix)
DEF_SCENE_TYPE(SCENE_APP_TOP)
DEF_SCENE_TYPE(SCENE_APP_STARTMENU)
DEF_SCENE_TYPE(SCENE_LOADING)
DEF_SCENE_TYPE(SCENE_BIRTHDAY_TEXT)
DEF_SCENE_TYPE(SCENE_BIRTHDAY_PRINCE)
DEF_SCENE_TYPE(SCENE_BIRTHDAY_ANIM)
DEF_SCENE_TYPE(SCENE_LOADING_QUEST_BATTLE)
DEF_SCENE_TYPE(SCENE_LOGIN_BONUS)
DEF_SCENE_TYPE(SCENE_TOP_PAGE)
DEF_SCENE_TYPE(SCENE_QUEST_WORLDMAP)
DEF_SCENE_TYPE(SCENE_QUEST_TOP)
DEF_SCENE_TYPE(SCENE_QUEST_BATTLE)
DEF_SCENE_TYPE(SCENE_SHOP_TOP)
DEF_SCENE_TYPE(SCENE_SHOP_COIN)
DEF_SCENE_TYPE(SCENE_SHOP_ITEM)
//byshixc 添加月卡scene定义
DEF_SCENE_TYPE(SCENE_MONTH_CARD)
DEF_SCENE_TYPE(SCENE_FRIEND)
DEF_SCENE_TYPE(SCENE_COMMUNITY)
DEF_SCENE_TYPE(SCENE_OTHERS_MENU)
DEF_SCENE_TYPE(SCENE_MISSION_PANEL)
DEF_SCENE_TYPE(SCENE_SCENARIO)
DEF_SCENE_TYPE(SCENE_SCENARIO_PLAY_TOP)
DEF_SCENE_TYPE(SCENE_SCENARIO_SECOND_TOP)
DEF_SCENE_TYPE(SCENE_PRESENT_TOP)
DEF_SCENE_TYPE(SCENE_PRESENT_HISTORY)
DEF_SCENE_TYPE(SCENE_SERIAL_TOP)
DEF_SCENE_TYPE(SCENE_SERIAL_INPUT)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED)
DEF_SCENE_TYPE(SCENE_ITEMVIEW)
DEF_SCENE_TYPE(SCENE_OPTION)
DEF_SCENE_TYPE(SCENE_COLLABORATE_TOP)
//byshixc 添加王子排行定义
DEF_SCENE_TYPE(SCENE_VOTE_SYSTEM)
DEF_SCENE_TYPE(SCENE_VOTE_RANK_SYSTEM)
// クエスト
DEF_SCENE_TYPE(SCENE_QUEST_MAP_DETAIL)
DEF_SCENE_TYPE(SCENE_QUEST_LIST)
DEF_SCENE_TYPE(SCENE_SELECT_SUPPORTER)
DEF_SCENE_TYPE(SCENE_QUEST_MEMBER)
DEF_SCENE_TYPE(SCENE_SHOW_CHARA_DETAIL)
DEF_SCENE_TYPE(SCENE_CHARACTER_STORY_LIST)
DEF_SCENE_TYPE(SCENE_QUEST_RESULT_PLAYERINFO)
DEF_SCENE_TYPE(SCENE_LEVEL_UP)
DEF_SCENE_TYPE(SCENE_QUEST_RESULT)
DEF_SCENE_TYPE(SCENE_QUEST_RESULT_ITEMS)
DEF_SCENE_TYPE(SCENE_QUEST_FRIEND)
DEF_SCENE_TYPE(SCENE_GOT_CHARACTER)
DEF_SCENE_TYPE(SCENE_GOT_CHARACTER_DETAIL)

//メイン
DEF_SCENE_TYPE(INVALID_SCENE_NEW_CORRELATIVE_STORY)
DEF_SCENE_TYPE(INVALID_SCENE_NEW_SIDE_STORY)
DEF_SCENE_TYPE(SCENE_KEYQUEST_AREA)
DEF_SCENE_TYPE(SCENE_KEYQUEST_QUEST_LIST)

//パーティ
DEF_SCENE_TYPE(SCENE_PARTY_TOP)    //パーティトップページ
DEF_SCENE_TYPE(SCENE_PARTY_DETAIL) //パーティ詳細
DEF_SCENE_TYPE(SCENE_PARTY_ANIM)   //パーティアニメ

//ガチャ
DEF_SCENE_TYPE(SCENE_GACHA_TOP)        //ガチャトップ
DEF_SCENE_TYPE(SCENE_GACHA_ANIM)       //ガチャアニメ
DEF_SCENE_TYPE(SCENE_GACHA_EXCHANGE)   //ガチャリング交換
DEF_SCENE_TYPE(SCENE_GACHA_RESULT)     //ガチャ結果
DEF_SCENE_TYPE(SCENE_GACHA_PRINCE)     //ガチャ目玉王子

// 新規登録
DEF_SCENE_TYPE(SCENE_USE_POLICY)
DEF_SCENE_TYPE(SCENE_JOGA_MESSAAGE)
DEF_SCENE_TYPE(SCENE_JOGA_MESSAAGE_ZH)
DEF_SCENE_TYPE(SCENE_ATTENTION_SOUND)
DEF_SCENE_TYPE(SCENE_OPENING_MOVIE)
DEF_SCENE_TYPE(SCENE_ACCOUNT_TRANSFER)
DEF_SCENE_TYPE(SCENE_DOWNLOADING_DATA)
DEF_SCENE_TYPE(SCENE_LOADING_TIPS)
DEF_SCENE_TYPE(SCENE_PUBLISHER)
DEF_SCENE_TYPE(SCENE_FOX)
DEF_SCENE_TYPE(SCENE_TERMS)
DEF_SCENE_TYPE(SCENE_SOUND_ALERT)
DEF_SCENE_TYPE(SCENE_CHANGE_DEVICE_CHECK)
DEF_SCENE_TYPE(SCENE_FIRST_RESOURCE_DOWNLOAD)
DEF_SCENE_TYPE(SCENE_RESOURCE_DOWNLOAD)

// 王子関連
DEF_SCENE_TYPE(SCENE_PRINCE_TOP)
DEF_SCENE_TYPE(SCENE_PRINCE_TRAINING_TOP)
DEF_SCENE_TYPE(SCENE_PRINCE_TRAINING_ANIM)
DEF_SCENE_TYPE(SCENE_PRINCE_EVOLUTION_INDEX)
DEF_SCENE_TYPE(SCENE_PRINCE_EVOLUTION_SHOW)
DEF_SCENE_TYPE(SCENE_PRINCE_EVOLUTION_ANIM)
DEF_SCENE_TYPE(SCENE_PRINCE_TENDING_SHOW)
DEF_SCENE_TYPE(SCENE_PRINCE_LIST_ALL)
DEF_SCENE_TYPE(SCENE_PRINCE_GOODBY)
DEF_SCENE_TYPE(SCENE_PRINCE_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_STORY_LIST)
DEF_SCENE_TYPE(SCENE_PRINCE_FULL)
DEF_SCENE_TYPE(SCENE_DECK_TOP)
DEF_SCENE_TYPE(SCENE_DECK_MEMBER_SELECT)
DEF_SCENE_TYPE(SCENE_PRINCE_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_MAIN_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_MAIN_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_SIDE_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_SIDE_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_CORRELATIVE_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_CORRELATIVE_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_PRINCE_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_PRINCE_STORY_LIST)
DEF_SCENE_TYPE(SCENE_PRINCE_PRINCE_STORY_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_EVENT_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_EVENT_STORY_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_GALLERY)
DEF_SCENE_TYPE(SCENE_PRINCE_GALLERY_DETAIL)
DEF_SCENE_TYPE(SCENE_PRINCE_REWARD_ALBUM)
DEF_SCENE_TYPE(SCENE_PRINCE_REWARD_MEMORY)
DEF_SCENE_TYPE(SCENE_PRINCE_REWARD_MEET)
DEF_SCENE_TYPE(SCENE_PRINCE_AREA_STORY)
DEF_SCENE_TYPE(SCENE_PRINCE_GENERAL_STORY_LIST)
DEF_SCENE_TYPE(SCENE_DECK_SELECT_ATONCE)


// プレイヤー情報
DEF_SCENE_TYPE(SCENE_PLAYER_INFO)

// ヘルプ
DEF_SCENE_TYPE(SCENE_HELP_LIST)
DEF_SCENE_TYPE(SCENE_HELP_PAGE)
DEF_SCENE_TYPE(SCENE_HELP_WEB)

//スコアモード
DEF_SCENE_TYPE(SCENE_SCORE_MODE_TOP)
DEF_SCENE_TYPE(SCENE_SCORE_MODE_TITLE)
DEF_SCENE_TYPE(SCENE_SCORE_MODE_TITLE_UP)
DEF_SCENE_TYPE(SCENE_SCORE_MODE_SELECT)
DEF_SCENE_TYPE(SCENE_SCORE_MODE_RESULT)
DEF_SCENE_TYPE(SCENE_SCORE_MODE_RANK_UP)
DEF_SCENE_TYPE(SCENE_SCORE_MODE_HIGH_SCORE)

// ギルド
DEF_SCENE_TYPE(SCENE_GUILD_TOP)
DEF_SCENE_TYPE(SCENE_GUILD_MEMBER)
DEF_SCENE_TYPE(SCENE_GUILD_MEMBER_MANAGE)
DEF_SCENE_TYPE(SCENE_GUILD_NEWS)
DEF_SCENE_TYPE(SCENE_GUILD_CHAT)
DEF_SCENE_TYPE(SCENE_GUILD_ENTRY_INBOX)
DEF_SCENE_TYPE(SCENE_GUILD_INVITATION_SEARCH_TOP)
DEF_SCENE_TYPE(SCENE_GUILD_INVITATION_SEARCH_RESULT)
DEF_SCENE_TYPE(SCENE_GUILD_INVITATION_OUTBOX)
DEF_SCENE_TYPE(SCENE_GUILD_MANAGEMENT_MENU)
DEF_SCENE_TYPE(SCENE_GUILD_CONFIG)
DEF_SCENE_TYPE(SCENE_GUILD_ENTRANCE)
DEF_SCENE_TYPE(SCENE_GUILD_CREATION)
DEF_SCENE_TYPE(SCENE_GUILD_INVITATION_INBOX)
DEF_SCENE_TYPE(SCENE_GUILD_ENTRY_SEARCH_TOP)
DEF_SCENE_TYPE(SCENE_GUILD_ENTRY_SEARCH_RESULT)
DEF_SCENE_TYPE(SCENE_GUILD_AWAITING)
DEF_SCENE_TYPE(SCENE_GUILD_FACILITY_LIST)
DEF_SCENE_TYPE(SCENE_GUILD_FACILITY_INVEST)
DEF_SCENE_TYPE(SCENE_GUILD_FACILITY_INVEST_RECORD)

// チュートリアル
DEF_SCENE_TYPE(SCENE_TUTORIAL_BASE)
DEF_SCENE_TYPE(SCENE_TUTORIAL_QUEST_BATTLE)
DEF_SCENE_TYPE(SCENE_TUTORIAL_SECOND_QUEST_BATTLE)
DEF_SCENE_TYPE(SCENE_TUTORIAL_THIRD_QUEST_BATTLE)
DEF_SCENE_TYPE(SCENE_TUTORIAL_REGIST_NAME)
DEF_SCENE_TYPE(SCENE_TUTORIAL_PRINCE_SELECT)

//イベント
DEF_SCENE_TYPE(SCENE_EVENT_TOP)
DEF_SCENE_TYPE(SCENE_EVENT_RANKING)
DEF_SCENE_TYPE(SCENE_EVENT_REWARD)
DEF_SCENE_TYPE(SCENE_EVENT_ANIM)
DEF_SCENE_TYPE(SCENE_EVENT_ANIM_COIN)
DEF_SCENE_TYPE(SCENE_EVENT_ANIM_STORY_REWARD)
DEF_SCENE_TYPE(SCENE_EVENT_COMMUNITY_TOP)
DEF_SCENE_TYPE(SCENE_EVENT_COMMUNITY_RANKING)
DEF_SCENE_TYPE(SCENE_EVENT_COMMUNITY_REWARD)
DEF_SCENE_TYPE(SCENE_AWARD_EVENT_TOP)
DEF_SCENE_TYPE(SCENE_AWARD_EVENT_NOMINATED_LIST)
DEF_SCENE_TYPE(SCENE_AWARD_EVENT_NOMINATED_DETAIL)
DEF_SCENE_TYPE(SCENE_AWARD_EVENT_FAVORITES_LIST)
DEF_SCENE_TYPE(SCENE_AWARD_EVENT_REWARD_LIST)

// でばっぐ
#ifdef VITAMIN_DEBUG_TOOL_ENABLE
DEF_SCENE_TYPE(SCENE_DEBUG_TOP)
DEF_SCENE_TYPE(SCENE_DEBUG_EMOTIONAL_PRINCE)
DEF_SCENE_TYPE(SCENE_DEBUG_FULLSIZE_PRINCE)
DEF_SCENE_TYPE(SCENE_DEBUG_STORY_LIST)
DEF_SCENE_TYPE(SCENE_DEBUG_SPINE_VIEWER)
DEF_SCENE_TYPE(SCENE_DEBUG_SOUND)
DEF_SCENE_TYPE(SCENE_DEBUG_SCENARIO_PRINCE)
DEF_SCENE_TYPE(SCENE_DEBUG_PROVISIONAL_SCENE)
DEF_SCENE_TYPE(SCENE_DEBUG_PROVISIONAL_PARTS_SCENE)
#endif  /* ifdef VITAMIN_DEBUG_TOOL_ENABLE */

// ミッションパネル
DEF_SCENE_TYPE(SCENE_MISSION_PANEL_ANIME)
DEF_SCENE_TYPE(SCENE_MISSION_REWARD_DETAIL)

//フレンド
DEF_SCENE_TYPE(SCENE_FRIEND_INTRODUCTION)
DEF_SCENE_TYPE(SCENE_FRIEND_MAIL_LIST)

//メンテナンス
DEF_SCENE_TYPE(SCENE_MAINTENANCE)

// レイド
DEF_SCENE_TYPE(SCENE_RAID_EVENT_TOP)
DEF_SCENE_TYPE(SCENE_RAID_BOSS_LIST)
DEF_SCENE_TYPE(SCENE_RAID_BATTLE_TOP)
DEF_SCENE_TYPE(SCENE_RAID_REWARD)
DEF_SCENE_TYPE(SCENE_RAID_RESCUE_MEMBER)
DEF_SCENE_TYPE(SCENE_SHOP_LIMITED_ITEM)  // 限定アイテム

// チケット交換所
DEF_SCENE_TYPE(SCENE_TICKET_EXCHANGE)

// シーンIDが変わらないよう末尾に追加
DEF_SCENE_TYPE(SCENE_LOGIN_JACK)
DEF_SCENE_TYPE(SCENE_RESTORE_ENTRANCE)
DEF_SCENE_TYPE(SCENE_RESTORE_ACCOUNT)
DEF_SCENE_TYPE(SCENE_RESTORE_ACCOUNT_RESULT)
DEF_SCENE_TYPE(SCENE_SNS_INTEGRATION)
DEF_SCENE_TYPE(SCENE_SNS_INTEGRATION_RESULT)
DEF_SCENE_TYPE(SCENE_SNS_INTEGRATION_TERMS)

DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_TOP)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_GUID)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_ISSUE)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_ISSUED)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_CONFIRM)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_SNS_BEFORE)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_SNS_AFTER)
DEF_SCENE_TYPE(SCENE_TAKEOVER_INTEGRATED_SNS_CANCEL)

DEF_SCENE_TYPE(SCENE_WAREHOUSE_TOP)
DEF_SCENE_TYPE(SCENE_WAREHOUSE_MEMBER_REPLACE)

DEF_SCENE_TYPE(SCENE_JEWEL_EXCHANGE)
DEF_SCENE_TYPE(SCENE_OPEN_TREASURE_CHEST)

DEF_SCENE_TYPE(SCENE_SUGGESTIONBOX_TOP)
DEF_SCENE_TYPE(SCENE_SUGGESTIONBOX_POST)
DEF_SCENE_TYPE(SCENE_HELP_FAQ_TOP)

DEF_SCENE_TYPE(SCENE_NEW_STORY_LIST)

DEF_SCENE_TYPE(SCENE_LAST)

#else

#ifndef __VitaminProject__VitaminSceneID_h
#define __VitaminProject__VitaminSceneID_h

#define kVitaminSceneIDPrefix       0x00000000
#define DEF_SCENE_TYPE(name)        name,
#define DEF_SCENE_TYPE_1(name, val) name = val,

#include "ISceneManager.h"
enum VitaminSceneType : SceneID {
#include "VitaminSceneID.h"
};

#undef DEF_SCENE_TYPE
#undef DEF_SCENE_TYPE_1

#endif
#endif // __VitaminProject__VitaminSceneID_h
